### ISSUE TITLE
Create parser/scraper for chosen data set

### ISSUE THREAD

**Issue by wegrata** [bdeezz/Directed_Study#7]
Create a script that parses the data (xml for stackoverflow, csv for kaggle) or that scrapes the txt files from textfiles.com and loads them into hdfs

**Comment by bdeezz** [comment]
Look at python and requests and py-query or scala and akka-http client

**Comment by bdeezz** [comment]
Download Food files from textfiles.com
href in anchor tags 
use textfiles.com/Food
